In [845]:
import numpy as np
import pandas as pd

In [846]:
legajo_tarjeta = pd.read_excel('ListadoLegajos20-1-2023 8.37.24.xls', )
legajo_tarjeta

,Nro Identificador,Nro Tarjeta,Apellido y Nombre,Privilegio,Clave,Cant. Huellas,Habilitado
0,9,11,ADMIN,Super administrador,5555,0,Si
1,10,,ADMIN,Super administrador,5555,0,Si
2,16,,ADMIN,Super administrador,5555,0,Si
3,17,,ADMIN,Super administrador,5555,0,Si
4,18,,ADMIN,Super administrador,5555,0,Si
...,...,...,...,...,...,...,...
1519,9139,111335,CEI FACU,Empleado,0555,0,Si
1520,9140,111536,lopez wa,Empleado,9140,0,Si
1521,9142,123563,FORTUNOF,Empleado,,0,Si
1522,60202,0000122100,VILLAMOR,Empleado,60202,0,Si
1523,60206,5512167,SOLIS NO,Empleado,60206,0,Si

In [847]:
usuario_reloj = pd.read_excel('usuario_reloj.xlsx', )
usuario_reloj

,legajo,apellido,nombre,tipo_doc,nro_doc,fecnac,domicilio,nro,localidad,antiguedad,...,descripcion,nro.1,ruta_archivo,clave_activacion,nro_serie,direccion_ip,usuario,pass,leer_fichada,activado
0,577,COLON,NORMA BEATRIZ,DNI,17585757,1966-07-08,CURIE,320.0,1,2000-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
1,617,MARTINEZ,GRISELDA MARIELA,DNI,22917962,1973-03-28,VIGNAU,1566.0,1,2005-10-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
2,625,TAVOLONI,GABRIELA,DNI,22800094,1972-05-31,SARMIENTO,176.0,1,2008-07-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
3,649,GONZALEZ,SILVIA NOEM,DNI,13974459,1960-02-03,BROWN,183.0,1,2001-04-24,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
4,691,ROBURU,CLAUDIO OSCAR,DNI,20359535,1968-06-20,12 DE ABRIL,624.0,1,2013-06-03,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,9134,DIAZ,MARIA EUGENIA,DNI,37033426,1992-10-21,UGARTE,360.0,1,2023-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
247,9135,DANS,NATACHA BELEN,DNI,38769819,1995-04-18,JOSE HERNANDEZ,128.0,1,2023-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
248,9136,GOMEZ,MARIA VICTORIA,DNI,37016552,1992-06-23,LEON XII,510.0,1,2023-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
249,9137,SERVERA,EVELYN AGUSTINA,DNI,38083073,1994-01-21,MARCONI,25.0,1,2023-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
250,9142,FORTUNOFF,FACUNDO IVAN,DNI,42294451,2000-01-19,MARCONI,1132.0,1,2023-01-01,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1

In [848]:
inner = pd.merge(left=legajo_tarjeta, right=usuario_reloj, left_on='Nro Identificador', right_on='legajo')
inner

,Nro Identificador,Nro Tarjeta,Apellido y Nombre,Privilegio,Clave,Cant. Huellas,Habilitado,legajo,apellido,nombre,...,descripcion,nro.1,ruta_archivo,clave_activacion,nro_serie,direccion_ip,usuario,pass,leer_fichada,activado
0,577,0005138594,COLON NO,Empleado,577,0,Si,577,COLON,NORMA BEATRIZ,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
1,617,0000098570,MARTINEZ,Empleado,617,0,Si,617,MARTINEZ,GRISELDA MARIELA,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
2,625,0000120850,TAVOLONI,Empleado,625,0,Si,625,TAVOLONI,GABRIELA,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
3,649,0007220073,GONZALEZ,Empleado,649,0,Si,649,GONZALEZ,SILVIA NOEM,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
4,691,0000111134,RODURU C,Empleado,691,0,Si,691,ROBURU,CLAUDIO OSCAR,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246,9134,85212,DIAZ EUG,Empleado,,0,Si,9134,DIAZ,MARIA EUGENIA,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
247,9135,89982,DANS NAT,Empleado,,0,Si,9135,DANS,NATACHA BELEN,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
248,9136,91965,GOMEZ MA,Empleado,,0,Si,9136,GOMEZ,MARIA VICTORIA,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
249,9137,122921,SERVERA,Empleado,,0,Si,9137,SERVERA,EVELYN AGUSTINA,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1
250,9142,123563,FORTUNOF,Empleado,,0,Si,9142,FORTUNOFF,FACUNDO IVAN,...,Hospital,5,\\192.168.100.31\ControlPersonalv2\Importacion...,BCBVUJJXXJ,1458629380076,100.100.100.198,NaN,NaN,1,1

## Extract useful data

In [849]:
for_export = inner[['Nro Identificador', 'Nro Tarjeta', 'apellido',
                    'nombre', 'fecnac', 'antiguedad', 'domicilio', 'nro']]
for_export['nro'][for_export['nro'].isnull()] = 0
for_export['nro'][for_export['nro'] == 0] 
for_export['nro'] = for_export['nro'].astype(np.intc)

/tmp/ipykernel_1177/4184416748.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['nro'][for_export['nro'].isnull()] = 0
/tmp/ipykernel_1177/4184416748.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['nro'][for_export['nro'].isnull()] = 0
/tmp/ipykernel_1177/4184416748.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['nro'] = for_export['nro'].astype(np.intc)

## Concatenate last name and name, then delete the columns

In [850]:

for_export['Nombre'] = for_export.apply(
    lambda x: x['apellido'] + ' ' + x['nombre'], axis=1)
del for_export['nombre']
del for_export['apellido']

/tmp/ipykernel_1177/1771085200.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['Nombre'] = for_export.apply(

## Concatenate address and number, the delete the columns

In [851]:
for_export['Domicilio'] = for_export.apply(
    lambda x: x['domicilio'] + ' ' + str(x['nro']), axis=1)
del for_export['domicilio']
del for_export['nro']

/tmp/ipykernel_1177/667258676.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['Domicilio'] = for_export.apply(

## Add user number

In [852]:
length = for_export.shape[0]
for_export['Usuario Nro.'] = np.arange(1, length + 1)

/tmp/ipykernel_1177/88976462.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['Usuario Nro.'] = np.arange(1, length + 1)

## Add needed columns

In [853]:
for_export['GÃ©nero'] = np.nan
for_export['Departamento'] = 'Hospital'
for_export['PosiciÃ³n'] = np.nan
for_export['TelÃ©fono'] = np.nan
for_export['Dispositivos'] = np.nan

/tmp/ipykernel_1177/3061358718.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['GÃ©nero'] = np.nan
/tmp/ipykernel_1177/3061358718.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['Departamento'] = 'Hospital'
/tmp/ipykernel_1177/3061358718.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['PosiciÃ³n'] = np.nan
/tmp/ipykernel_1177/3061358718.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['TelÃ©fono'] = np.nan
/tmp/ipykernel_1177/3061358718.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['Dispositivos'] = np.nan

## Correct columns types

In [854]:
for_export['fecnac'] = for_export['fecnac'].astype(str)
for el in for_export['fecnac']:
    el = el[6:16]
for_export['antiguedad'] = for_export['antiguedad'].astype(str)
for el in for_export['antiguedad']:
    el = el[6:16]

/tmp/ipykernel_1177/495002138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['fecnac'] = for_export['fecnac'].astype(str)
/tmp/ipykernel_1177/495002138.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  for_export['antiguedad'] = for_export['antiguedad'].astype(str)

28     NaT
106    NaT
167    NaT
231    NaT
Name: fecnac, dtype: object

## Rename columns

In [855]:
for_export = for_export.rename(columns={"Nro Identificador": "ID en dispositivo", "Nro Tarjeta": "Tarjeta Nro.", "fecnac": "CumpleaÃ±os", "antiguedad": "Fecha de inicio laboral", "B": "c"})

## Generate final output

In [887]:
final_dataframe = for_export[['Usuario Nro.', 'ID en dispositivo', 'Tarjeta Nro.', 'Nombre',
                              'Departamento', 'GÃ©nero', 'PosiciÃ³n', 'CumpleaÃ±os', 'Fecha de inicio laboral', 'TelÃ©fono', 'Domicilio', 'Dispositivos']]
final_dataframe.fillna('', inplace=True)
final_dataframe.loc[final_dataframe['CumpleaÃ±os'] == 'NaT', 'CumpleaÃ±os'] = '1990-01-01'
final_dataframe.to_excel('Reloj Hospital.xlsx', index=False)
final_dataframe[17:45][['CumpleaÃ±os', 'Nombre']]

    CumpleaÃ±os                    Nombre
17  1959-04-19      VAZQUEZ TERESA CRIST
18  1960-08-04          CASTAÃ‘O GRACIELA
19  1965-01-02       PEDERNERA MARIA DEL
20  1963-07-13      HERNANDEZ CLARA BEAT
21  1966-09-28          TAPIA MARIA ROSA
22  1967-11-02        QUESSI NILDA SONIA
23  1964-02-27      PLANES MARIA ANTONIA
24  1969-03-24      ALBINO FABIO IMPERIO
25  1965-02-22         ADRIEL NORA MABEL
26  1960-07-20      CANDO AMELIA MATILDE
27  1961-12-14      RODRIGUEZ MIRTA GRIS
28  1990-01-01                1990-01-01
29  1964-11-17         TACUNAU ANA MARIA
30  1972-07-12      BARREDO MONICA ROSAN
31  1963-05-30           IBAÃ‘EZ ELBA NOE
32  1961-02-21        MAGUNA MARTA LUCIA
33  1973-05-16         LEDESMA ANA MARIA
34  1966-08-14      BANEGA CLAUDIA LILIA
35  1969-11-03      ESPINDOLA LAURA FERN
36  1975-06-03      PEREZ VERONICA EDITH
37  1967-11-01       VERDI LEONARDO HUGO
38  1970-07-21      DODDATE ALICIA ESTHE
39  1960-10-02      CASCALLAR MARIA ISAB
40  1977-06-05       NIEVAS LAURA VANINA
41  1974-06-01      MONTES MARIELA VANES
42  1977-07-17  MANSILLA VERONICA MARISA
43  1983-02-02         LUNA SARA DANIELA
44  1968-10-03        SANCHEZ MARIA INES